remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [CC]
description: [A collection of all my work related certificates, gathered throughout the years]

show_downloads: [true]